# Generated by Django 3.0.6 on 2020-06-12 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('summary', models.CharField(blank=True, max_length=150, null=True)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('wrld', 'WORLD'), ('tech', 'TECHNOLOGY'), ('desgn', 'DESIGN'), ('bus', 'BUSSINESS'), ('pol', 'POLITICS'), ('hlth', 'HEALTH'), ('tr', 'TRAVEL')], max_length=40)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_pic')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
