# Generated by Django 3.0.6 on 2020-06-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
