# Generated by Django 3.0.6 on 2020-11-13 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comments_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
