# Generated by Django 3.0.6 on 2020-11-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_featuredpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredpost',
            name='post',
        ),
        migrations.AddField(
            model_name='featuredpost',
            name='post',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
