# Generated by Django 3.0.6 on 2020-11-21 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201121_0124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeaturedPost',
        ),
    ]
